In [ ]:
# dataset = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Datasets/complaints-2021-05-14_08_16.json')

In [ ]:
# dataset.replace(["", "N/A"], np.nan, inplace=True)

In [ ]:
# flatten dataset _source into another table
# source_set = pd.json_normalize(dataset['_source'])
# source_set['complaint_id'] = source_set['complaint_id'].astype(int)
# source_set.replace(["", "N/A"], np.nan, inplace=True)
# maindf = dataset.merge(source_set, left_on='_id', right_on='complaint_id', how='inner')
# maindf.drop(columns=['_source'], inplace=True)
# maindf.head()

_index      _type      _id  _score           tags zip_code  \
0  complaint-public-v2  complaint  3211475       0           None    90301   
1  complaint-public-v2  complaint  3229299       0  Servicemember    319XX   
2  complaint-public-v2  complaint  3199379       0           None    77069   
3  complaint-public-v2  complaint  2673060       0           None    48066   
4  complaint-public-v2  complaint  3203545       0           None    10473   

   complaint_id                               issue  \
0       3211475   Attempts to collect debt not owed   
1       3229299     Written notification about debt   
2       3199379  Other features, terms, or problems   
3       2673060      Trouble during payment process   
4       3203545                    Fees or interest   

               date_received state  ...         company_response  \
0  2019-04-13T12:00:00-05:00    CA  ...  Closed with explanation   
1  2019-05-01T12:00:00-05:00    GA  ...  Closed with explanation   
2  2019-04-02T12:00:00-05:00    TX  ...  Closed with explanation   
3  2017-09-13T12:00:00-05:00    MI  ...  Closed with explanation   
4  2019-04-05T12:00:00-05:00    NY  ...  Closed with explanation   

                company submitted_via       date_sent_to_company  \
0  JPMORGAN CHASE & CO.           Web  2019-04-13T12:00:00-05:00   
1  JPMORGAN CHASE & CO.           Web  2019-05-01T12:00:00-05:00   
2  JPMORGAN CHASE & CO.           Web  2019-04-02T12:00:00-05:00   
3  JPMORGAN CHASE & CO.           Web  2017-09-14T12:00:00-05:00   
4  JPMORGAN CHASE & CO.      Referral  2019-04-05T12:00:00-05:00   

  company_public_response                                 sub_product timely  \
0                    None                            Credit card debt    Yes   
1                    None                            Credit card debt    Yes   
2                    None  General-purpose credit card or charge card    Yes   
3                    None                  Conventional home mortgage    Yes   
4                    None  General-purpose credit card or charge card    Yes   

                             complaint_what_happened  \
0                                                NaN   
1  Good morning my name is XXXX XXXX and I apprec...   
2  I upgraded my XXXX XXXX card in XX/XX/2018 and...   
3                                                NaN   
4                                                NaN   

                                          sub_issue consumer_consent_provided  
0                                 Debt is not yours      Consent not provided  
1  Didn't receive enough information to verify debt          Consent provided  
2             Problem with rewards from credit card          Consent provided  
3                                              None      Consent not provided  
4                         Charged too much interest                       NaN  

[5 rows x 22 columns]

In [ ]:
# maindf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78313 entries, 0 to 78312
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   _index                     78313 non-null  object
 1   _type                      78313 non-null  object
 2   _id                        78313 non-null  int64 
 3   _score                     78313 non-null  int64 
 4   tags                       10900 non-null  object
 5   zip_code                   71556 non-null  object
 6   complaint_id               78313 non-null  int64 
 7   issue                      78313 non-null  object
 8   date_received              78313 non-null  object
 9   state                      76322 non-null  object
 10  consumer_disputed          42630 non-null  object
 11  product                    78313 non-null  object
 12  company_response           78313 non-null  object
 13  company                    78313 non-null  object
 14  submit

In [ ]:
# removing columns and rows
# cols = ['_index', 'complaint_id', 'issue', 'sub_issue', 'complaint_what_happened']
# cleandf = maindf[cols]
# cleandf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78313 entries, 0 to 78312
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   _index                   78313 non-null  object
 1   complaint_id             78313 non-null  int64 
 2   issue                    78313 non-null  object
 3   sub_issue                32016 non-null  object
 4   complaint_what_happened  21072 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.6+ MB


In [ ]:
# cleandf.isna().sum()

_index                         0
complaint_id                   0
issue                          0
sub_issue                  46297
complaint_what_happened    57241
dtype: int64

In [ ]:
# clean2 = cleandf.dropna(subset=['complaint_what_happened'])

# df = clean2.drop(['sub_issue', '_index', 'complaint_id'], axis=1)

# df.info()

# df.to_json('ticket_cleaned.json', orient='records')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21072 entries, 1 to 78312
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   issue                    21072 non-null  object
 1   complaint_what_happened  21072 non-null  object
dtypes: object(2)
memory usage: 493.9+ KB


**Model**
**Attempt 1: Gaussian Naive Bayes**

In [2]:
!pip install swifter
!pip install contractions
!pip install -U gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 13.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for swifter: filename=swifter-1.4.0-py3-none-any.whl size=16510 sha256=a2094afc3b1f4ae5abaec1ceac3f321afaf2f4992a47812e86b8264b510e1198
  Stored in directory: /root/.cache/pip/wheels/e4/cf/51/0904952972ee2c7aa3709437065278dc534ec1b8d2ad41b443
Successfully built swifter
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 10.7 MB/s eta 0:00:00


In [3]:
import swifter

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import re, nltk, spacy, string
model = spacy.load("en_core_web_sm")
import en_core_web_sm
nlp = en_core_web_sm.load()

# corpus wordnet
nltk.download("wordnet")
# corpus punkt
nltk.download("punkt")
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
from nltk.corpus import stopwords

from nltk import pos_tag, word_tokenize

from nltk.stem import WordNetLemmatizer

from gensim.corpora.dictionary import Dictionary
from gensim.models.nmf import Nmf
from gensim.models.coherencemodel import CoherenceModel
from operator import itemgetter

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

from textblob import TextBlob

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [4]:
df = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Datasets/ticket_cleaned.json')
dfc = df.drop(columns=['issue'])

dfc.rename(columns={'complaint_what_happened' : 'complaints'}, inplace=True)




In [5]:
df.sample(20)

issue  \
17935                         Struggling to pay mortgage   
2727   Problem with a lender or other company chargin...   
1943                      Trouble during payment process   
12881                               Closing your account   
9559   Problem with a lender or other company chargin...   
20582                               Closing your account   
5042   Problem with a credit reporting company's inve...   
12153                                 Closing an account   
4693                               Closing on a mortgage   
1697                   Attempts to collect debt not owed   
8954                        Settlement process and costs   
1656   Took or threatened to take negative or legal a...   
5067               Customer service / Customer relations   
14601                         Managing the loan or lease   
2476               Problems caused by my funds being low   
9462     Problem with a purchase shown on your statement   
13220                                 Closing an account   
4924     Problem with a purchase shown on your statement   
8825                         Improper use of your report   
13017           Loan servicing, payments, escrow account   

                                 complaint_what_happened  
17935  They claim to have contacted me on certain dat...  
2727   I purchased 4 tickets through XXXX exchange. I...  
1943   As attached document illustrates, I currently ...  
12881  Chase closed two of my credit cards on XX/XX/2...  
9559   I think my identity has been compromised. I am...  
20582  Chase encouraged me to add authorized users on...  
5042   To whom this concerns, JPMorgan Chase has not ...  
12153  In XX/XX/2021, chase closed all my bank accoun...  
4693   This account should be in my exhusband name on...  
1697   Im a victim of identity theft someone got my J...  
8954   I filed a complain against Chase Mortgage on X...  
1656   See uploaded document dated XXXX ; CHASE BANK ...  
5067   I have had an ongoing issue with Chase pertain...  
14601  Chase auto finance has repeatedly refused to r...  
2476   I received my statement from chase, And the fu...  
9462   Our Chase Bank Card VISA card and another VISA...  
13220  I opened complaint XXXX about checking account...  
4924   Back in XX/XX/2019 a company called XXXX charg...  
8825                               Unauthorized inquiry.  
13017  Upon calculation of our monthly interest we ha...

In [ ]:
def cleaner(data):
  data = data.lower()
  data = re.sub(r'\[|\]',"",data)    # Remove text in square brackets
  data = re.sub(r'[^\w\s]',"",data)  # Remove punctuation
  data = re.sub(r'\w*\d\w*',"",data) # Remove words containing numbers
  return " ".join(data.split())  # Remove unwanted empty spaces

dfc['complaints'] = dfc['complaints'].swifter.apply(cleaner)

Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

In [ ]:
dfc['complaints'].iloc[1]

'i upgraded my xxxx xxxx card in and was told by the agent who did the upgrade my anniversary date would not change it turned the agent was giving me the wrong information in order to upgrade the account xxxx changed my anniversary date from xxxxxxxx to xxxxxxxx without my consent xxxx has the recording of the agent who was misled me'

In [ ]:
def checkFrequency(text):
  return len(str(text).split(' ')) # sentence to list

dfc['wordFrequency'] = dfc['complaints'].swifter.apply(checkFrequency)

dfc['wordFrequency'].describe()


Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

count    21072.000000
mean       243.966211
std        259.961767
min          1.000000
25%         93.000000
50%        175.000000
75%        308.000000
max       5276.000000
Name: wordFrequency, dtype: float64

In [ ]:
dfc.head(5)

complaints  wordFrequency
0  good morning my name is xxxx xxxx and i apprec...             90
1  i upgraded my xxxx xxxx card in and was told b...             62
2  chase card was reported on however fraudulent ...             31
3  on while trying to book a xxxx xxxx ticket i c...            263
4  my grand son give me check for i deposit it in...             92

In [ ]:
def lemmatize_text(text):
  lemmatized =[]
  doc = nlp(text)
  for word in doc:
    lemmatized.append(word.lemma_)
  return " ".join(lemmatized)

def get_nouns(text):
  blob = TextBlob(text)
  return ' '.join([ word for (word,tag) in blob.tags if tag == "NN"])


dfc['lemmatized complaints'] = dfc['complaints'].swifter.apply(lemmatize_text)

Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

In [ ]:
dfc['lemmatized complaints'] = dfc['lemmatized complaints'].swifter.apply(get_nouns)

Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

In [ ]:
df_clean = dfc[['complaints', 'lemmatized complaints']].copy()

df_clean.head()

complaints  \
0  good morning my name is xxxx xxxx and i apprec...   
1  i upgraded my xxxx xxxx card in and was told b...   
2  chase card was reported on however fraudulent ...   
3  on while trying to book a xxxx xxxx ticket i c...   
4  my grand son give me check for i deposit it in...   

                               lemmatized complaints  
0  morning name stop bank cardmember service ask ...  
1  card agent upgrade date agent information orde...  
2  card report application identity consent servi...  
3  try book xxxx ticket offer ticket card informa...  
4  son chase account fund bank account pay money ...

In [ ]:
def extract_POS_tags(data):
  nouns = [token for token, pos in pos_tag(word_tokenize(data)) if pos.startswith('N')]
  return ' '.join(nouns)

df_clean['complaints_POS_removed'] = dfc['lemmatized complaints'].swifter.apply(extract_POS_tags)

Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

In [ ]:
df_clean.head()

complaints  \
0  good morning my name is xxxx xxxx and i apprec...   
1  i upgraded my xxxx xxxx card in and was told b...   
2  chase card was reported on however fraudulent ...   
3  on while trying to book a xxxx xxxx ticket i c...   
4  my grand son give me check for i deposit it in...   

                               lemmatized complaints  \
0  morning name stop bank cardmember service ask ...   
1  card agent upgrade date agent information orde...   
2  card report application identity consent servi...   
3  try book xxxx ticket offer ticket card informa...   
4  son chase account fund bank account pay money ...   

                              complaints_POS_removed  
0  morning name bank cardmember service debt veri...  
1  card agent date agent information order accoun...  
2  report application identity consent service cr...  
3  book xxxx ticket offer ticket card information...  
4  son chase account fund bank account money son ...

In [ ]:
df_clean['complaintsClean'] = df_clean['complaints_POS_removed'].str.replace('xxxx','')

def remove_allXX(text):
  return re.sub('[x]{2,}',"",text)

df_clean['complaintsClean'] = df_clean['complaintsClean'].swifter.apply(remove_allXX)

Pandas Apply:   0%|          | 0/21072 [00:00<?, ?it/s]

In [ ]:
df_clean.sample(10)

complaints  \
3193   on xxxx xxxxxxxx i requested a refund of from ...   
12996  i changed cable providers based on the underst...   
13910  sometime early xxxxxxxx after moving to the us...   
14521  i had xxxx charges this year by xxxx i dispute...   
17162  in the first week xxxxxxxx a representative fr...   
2485   i filed for personal bankruptcy in i understoo...   
8917   on xxxxxxxx i contact xxxx xxxx about a fraudu...   
12296  i request a xxxx statement xxxx xxxx of xxxx i...   
19724  i never had a credit card that was in this lar...   
10711  i am xxxx years old with over credit score and...   

                                   lemmatized complaints  \
3193   refund notice amount account dispute bank refu...   
12996  cable provider base understanding box definiti...   
13910  xxxxxxxx move usa xxxx connection chase accoun...   
14521  charge year xxxx bank item bank work company f...   
17162  week representative phone insurance policy inc...   
2485   bankruptcy lawyer mortgage filing problem equi...   
8917   xxxxxxxx xxxx bank wire account bank purchase ...   
12296  statement statement statement statement month ...   
19724  credit card amount card limit offer amount pro...   
10711  year credit score account property bank chase ...   

                                  complaints_POS_removed  \
3193   refund notice amount bank refund card refund c...   
12996  cable provider base definition tv internet ser...   
13910  move usa xxxx connection chase account letter ...   
14521  charge year xxxx bank item bank work company c...   
17162  week representative phone insurance policy inc...   
2485   bankruptcy lawyer mortgage filing problem equi...   
8917   xxxxxxxx xxxx bank wire account bank purchase ...   
12296  statement statement statement statement month ...   
19724  credit card amount card limit offer amount pro...   
10711  year credit score account property bank year c...   

                                         complaintsClean  
3193   refund notice amount bank refund card refund c...  
12996  cable provider base definition tv internet ser...  
13910  move usa  connection chase account letter chas...  
14521  charge year  bank item bank work company compa...  
17162  week representative phone insurance policy inc...  
2485   bankruptcy lawyer mortgage filing problem equi...  
8917     bank wire account bank purchase truck amount...  
12296  statement statement statement statement month ...  
19724  credit card amount card limit offer amount pro...  
10711  year credit score account property bank year c...

**FEATURE EXTRACTION : USING NON-NEGATIVE MATRIX FACTORIZATION (NMF)**

In [ ]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english') # 0.95 = 95% , ignore words repeated in 95% of complaints,

# 2 for min_df is the lower bound, ignore words infrequent, appearing in less than 2 complaints

In [ ]:
# create a doc term matrix : keeping track of words appearing in complaints, it wont have words that have a score of 0 , words that
# only appear in one complaint . that way we can find the most dominant terms in complaints and categorize based on that

dtm = tfidf.fit_transform(df_clean['complaintsClean'])

Topic Modelling : extracting words from complaints using nmf

In [ ]:
from sklearn.decomposition import NMF

# Use gensim's nmf model here

texts = df_clean['complaintsClean']

dataset = [d.split() for d in texts]

# Create a Dictionary to keep track of word occurance count

dictionary = Dictionary(dataset)

# filter out outliers

dictionary.filter_extremes(
    no_below=3,
    no_above=0.85,
    keep_n=5000
)


# create bag of words (token : count)

texts_corpus = [dictionary.doc2bow(text) for text in dataset]

# random issue topic list
topic_nums = list(np.arange(5, 10, 1)) # 5,6,7,8,9

coherence_scores = []

for num in topic_nums:
    nmf = Nmf(
        corpus=texts_corpus,
        num_topics=num,
        id2word=dictionary,
        chunksize=2000,
        passes=5,
        kappa=.1,
        minimum_probability=0.01,
        w_max_iter=300,
        w_stop_condition=0.0001,
        h_max_iter=100,
        h_stop_condition=0.001,
        eval_every=10,
        normalize=True,
        random_state=42
    )

    # run coherence model here
    cm = CoherenceModel(
        model=nmf,
        texts=texts,
        dictionary=dictionary,
        coherence='c_v'
    )

    coherence_scores.append(round(cm.get_coherence(), 5))

scores = list(zip(topic_nums, coherence_scores)) # zip maps both lists into one score list
best_num_issue_topics = sorted(scores, key=itemgetter(1), reverse=True)[0][0]

print(best_num_issue_topics)

5


**Hence 5 topics are the best to classify this data**

In [ ]:
# load sklearn's nmf model for trial and error approach

num_topics = 5 # say 5

# here random_state = 40 say
nmf_model = NMF(n_components=num_topics, random_state=40)

In [ ]:
nmf_model.fit(dtm)
len(tfidf.get_feature_names_out())

5798

In [ ]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['transfer', 'customer', 'claim', 'business', 'number', 'transaction', 'branch', 'day', 'chase', 'deposit', 'fund', 'check', 'money', 'bank', 'account']


THE TOP 15 WORDS FOR TOPIC #1
['balance', 'year', 'application', 'letter', 'debt', 'limit', 'information', 'score', 'company', 'account', 'chase', 'inquiry', 'report', 'card', 'credit']


THE TOP 15 WORDS FOR TOPIC #2
['history', 'car', 'year', 'mortgage', 'pay', 'credit', 'date', 'auto', 'time', 'day', 'fee', 'statement', 'month', 'balance', 'payment']


THE TOP 15 WORDS FOR TOPIC #3
['day', 'company', 'time', 'statement', 'service', 'claim', 'purchase', 'fraud', 'chase', 'merchant', 'dispute', 'transaction', 'fee', 'card', 'charge']


THE TOP 15 WORDS FOR TOPIC #4
['foreclosure', 'document', 'sale', 'bank', 'house', 'time', 'letter', 'rate', 'year', 'property', 'chase', 'modification', 'home', 'mortgage', 'loan']




In [ ]:
issue_results = nmf_model.transform(dtm)
issue_results[0].round(2)
issue_results[0].argmax()
issue_results.argmax(axis=1)

array([0, 1, 1, ..., 3, 2, 2])

In [ ]:
# assign this to a column

df_clean['Issue Index'] = issue_results.argmax(axis=1)

In [ ]:
df_clean = df_clean.groupby('Issue Index').head(8)
df_clean.sort_values('Issue Index')

complaints  \
0    good morning my name is xxxx xxxx and i apprec...   
18   chase sent me an email today with the innocuou...   
17   my card went missing and i didnt realize it un...   
15   i opened the saving account for the bonus i wa...   
12   i opened an account with chase bank on xxxx an...   
6    with out notice jp morgan chase restricted my ...   
10   mishandling of this account by chase auto and ...   
4    my grand son give me check for i deposit it in...   
9    i have a chase credit card which is incorrectl...   
11   i have reached out to xxxx several times in at...   
14   my chase amazon card was declined for a cateri...   
3    on while trying to book a xxxx xxxx ticket i c...   
2    chase card was reported on however fraudulent ...   
1    i upgraded my xxxx xxxx card in and was told b...   
5                        can you please remove inquiry   
21   i am a senior citizen that has been scammed by...   
92   on saturday xxxxxxxx and tuesday i used chase ...   
73   a double payment from my chase debt cart to ch...   
24   i made a purchase of on xxxxxxxx i made paymen...   
57   action taken by the company between the dates ...   
33   i recently called to ask chase bank why they r...   
111  i received an offer from chase xxxx visa promi...   
93   my mortgage is with chase my payments were bei...   
7    during the summer months i experience a declin...   
8    on xxxx i made a payment to an online retailer...   
13   to whom it may concern chase bank charged wron...   
38   on we purchased a service with xxxx xxxx xxxx ...   
36   i preordered an item on xxxxxxxx and paid with...   
19   i made a purchase with xxxx xxxx xxxx on in th...   
31   my dispute is for not receiving services liste...   
26   i tried to send almost at xxxx and the transac...   
16   xxxx xxxx a sofa love seat table and chairs an...   
32   i bought a new xxxx xxxx on xxxxxxxx from xxxx...   
23   i have been trying to do a loan modification w...   
47   i am xxxx military member xxxx with the xxxx c...   
67   chase issued a mortgage loan against my proper...   
30   i have wired through one of chase branches in ...   
87   i owe around to chase and am in a debt resolut...   
89   jp morgan and chase reported loans xxxx xxxx a...   
41   my name is xxxx xxxx i have missed a payment i...   

                                 lemmatized complaints  \
0    morning name stop bank cardmember service ask ...   
18   send email today title information regard chan...   
17              card today email money bank account go   
15   save account bonus bonus auto transfer check t...   
12   account bank code bonus term everything accoun...   
6    jp chase account debit card tuesday thursday b...   
10                         mishandle account auto xxxx   
4    son chase account fund bank account pay money ...   
9    chase credit card datum credit report company ...   
11   time attempt inquiry creditor place inquiry re...   
14   chase card decline catering order place brothe...   
3    try book xxxx ticket offer ticket card informa...   
2    card report application identity consent servi...   
1    card agent upgrade date agent information orde...   
5                                              inquiry   
21   citizen company xxxx time share company nothin...   
92   tuesday pay payment security deposit month ren...   
73   payment debt cart credit card post request day...   
24   purchase xxxxxxxx payment xxxxxxxx payment clo...   
57   action company date individual group contact c...   
33   bank credit bureau day payment info xxxx bill ...   
111  offer companion airline pass bonus point card ...   
93   mortgage payment month provider xxxx xxxx tran...   
7    summer month income employment month payment e...   
8    xxxx payment online retailer use pay xxxx chas...   
13   concern bank charge fee balance fee balance tr...   
38   service group island snorkeling activity basis...   
36   item chase credit card merchant esti

In [ ]:
Issue_Dictionary = {
    0 : "Bank account and/or its services Issue",
    1 : "Credit card related Issue",
    2 : "Other Issues",
    3 : "Fraud or theft disputes",
    4 : "Mortgage and Loan Issue"
}

# map issue dict to column issues

df_clean['Issue_Category'] = df_clean['Issue Index'].map(Issue_Dictionary)

df_clean

complaints  \
0    good morning my name is xxxx xxxx and i apprec...   
1    i upgraded my xxxx xxxx card in and was told b...   
2    chase card was reported on however fraudulent ...   
3    on while trying to book a xxxx xxxx ticket i c...   
4    my grand son give me check for i deposit it in...   
5                        can you please remove inquiry   
6    with out notice jp morgan chase restricted my ...   
7    during the summer months i experience a declin...   
8    on xxxx i made a payment to an online retailer...   
9    i have a chase credit card which is incorrectl...   
10   mishandling of this account by chase auto and ...   
11   i have reached out to xxxx several times in at...   
12   i opened an account with chase bank on xxxx an...   
13   to whom it may concern chase bank charged wron...   
14   my chase amazon card was declined for a cateri...   
15   i opened the saving account for the bonus i wa...   
16   xxxx xxxx a sofa love seat table and chairs an...   
17   my card went missing and i didnt realize it un...   
18   chase sent me an email today with the innocuou...   
19   i made a purchase with xxxx xxxx xxxx on in th...   
21   i am a senior citizen that has been scammed by...   
23   i have been trying to do a loan modification w...   
24   i made a purchase of on xxxxxxxx i made paymen...   
26   i tried to send almost at xxxx and the transac...   
30   i have wired through one of chase branches in ...   
31   my dispute is for not receiving services liste...   
32   i bought a new xxxx xxxx on xxxxxxxx from xxxx...   
33   i recently called to ask chase bank why they r...   
36   i preordered an item on xxxxxxxx and paid with...   
38   on we purchased a service with xxxx xxxx xxxx ...   
41   my name is xxxx xxxx i have missed a payment i...   
47   i am xxxx military member xxxx with the xxxx c...   
57   action taken by the company between the dates ...   
67   chase issued a mortgage loan against my proper...   
73   a double payment from my chase debt cart to ch...   
87   i owe around to chase and am in a debt resolut...   
89   jp morgan and chase reported loans xxxx xxxx a...   
92   on saturday xxxxxxxx and tuesday i used chase ...   
93   my mortgage is with chase my payments were bei...   
111  i received an offer from chase xxxx visa promi...   

                                 lemmatized complaints  \
0    morning name stop bank cardmember service ask ...   
1    card agent upgrade date agent information orde...   
2    card report application identity consent servi...   
3    try book xxxx ticket offer ticket card informa...   
4    son chase account fund bank account pay money ...   
5                                              inquiry   
6    jp chase account debit card tuesday thursday b...   
7    summer month income employment month payment e...   
8    xxxx payment online retailer use pay xxxx chas...   
9    chase credit card datum credit report company ...   
10                         mishandle account auto xxxx   
11   time attempt inquiry creditor place inquiry re...   
12   account bank code bonus term everything accoun...   
13   concern bank charge fee balance fee balance tr...   
14   chase card decline catering order place brothe...   
15   save account bonus bonus auto transfer check t...   
16   xxxx love seat table chair charge bank claim f...   
17              card today email money bank account go   
18   send email today title information regard chan...   
19   purchase amount transaction dispute case bank ...   
21   citizen company xxxx time share company nothin...   
23       loan modification chase runaround payment doc   
24   purchase xxxxxxxx payment xxxxxxxx payment clo...   
26           transaction d service refund card account   
30   chase branch reinstatement amount bank order f...   
31   dispute service list night hotel xxxx transpor...   
32   xxxx xxxxxxxx loan title time resolution time ...   
33   bank credit bureau day payment info 

In [ ]:
training_data = df_clean[['complaintsClean', 'Issue Index']]

training_data

**split data and create models**

In [ ]:
X = training_data['complaintsClean']
y = training_data['Issue Index']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, stratify = y, random_state = 100)

In [ ]:
TF_IDF_vectorizer = TfidfVectorizer(stop_words = "english", ngram_range = (1, 3), max_df = 0.95, min_df = 2, max_features = 10000)
X_train = TF_IDF_vectorizer.fit_transform(X_train).toarray()
X_test = TF_IDF_vectorizer.transform(X_test).toarray()
print(len(TF_IDF_vectorizer.get_feature_names_out()))

163


In [ ]:
y_train.value_counts()/len(y_train)

4    0.2
0    0.2
2    0.2
1    0.2
3    0.2
Name: Issue Index, dtype: float64

In [ ]:
model_1 = LogisticRegression(class_weight = "balanced", random_state = 100, max_iter = 500, n_jobs = -1)
model_1.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=500, n_jobs=-1,
                   random_state=100)

In [ ]:
def model_evaluation(model) :
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)
  print("Accuracy score on train data :", accuracy_score(y_train, y_train_pred))
  print("Accuracy score on test data :", accuracy_score(y_test, y_test_pred), end = "\n\n")
  print("Confusion matrix for test data :", confusion_matrix(y_test, y_test_pred), end = "\n\n", sep = "\n")
  print("Classification report on test data  :", classification_report(y_test, y_test_pred), sep = "\n")

**Logistic Regression Model**

In [ ]:
model_evaluation(model_1)

Accuracy score on train data : 1.0
Accuracy score on test data : 0.8

Confusion matrix for test data :
[[1 0 1 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 1 0 1]]

Classification report on test data  :
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         2
           2       0.50      1.00      0.67         2
           3       1.00      1.00      1.00         2
           4       1.00      0.50      0.67         2

    accuracy                           0.80        10
   macro avg       0.90      0.80      0.80        10
weighted avg       0.90      0.80      0.80        10



In [ ]:
model_2 = MultinomialNB()
model_2.fit(X_train, y_train)

MultinomialNB()

**Multinomial Naive Bayes Model**

In [ ]:
model_evaluation(model_2)

Accuracy score on train data : 1.0
Accuracy score on test data : 0.7

Confusion matrix for test data :
[[1 0 1 0 0]
 [0 2 0 0 0]
 [0 0 1 1 0]
 [0 0 0 2 0]
 [0 0 1 0 1]]

Classification report on test data  :
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         2
           2       0.33      0.50      0.40         2
           3       0.67      1.00      0.80         2
           4       1.00      0.50      0.67         2

    accuracy                           0.70        10
   macro avg       0.80      0.70      0.71        10
weighted avg       0.80      0.70      0.71        10



In [ ]:
complaint = ["Not able to use my chase credit card for the past 3 days, for online purchasing. The card has not expired yet and I also have a good credit score. Please do look into this issue"]
print("The complaint falls into the category :", Issue_Dictionary.get(model_1.predict(TF_IDF_vectorizer.transform(complaint))[0]))

The complaint falls into the category : Credit card related Issue


In [ ]:
complaint = ["My loan application has been pending for weeks without any updates. This delay is causing significant inconvenience."]
print("The complaint falls into the category :", Issue_Dictionary.get(model_2.predict(TF_IDF_vectorizer.transform(complaint))[0]))

The complaint falls into the category : Mortgage and Loan Issue
